[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "2"
members = ["service", "migration", "entity"]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
