# docker-compose.yml
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  picktheday:
    image: picktheday:latest
    container_name: picktheday
    environment:
      DATABASE_URL: postgres://dev:devpassword@postgres:5432/devdb
    ports:
      - "4000:3000"

  test-postgres:
    image: postgres:17
    container_name: test-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: testdb
    ports:
      - "2345:5432"

volumes:
  pgdata:
    name: picktheday_dev_db