name: Build leptos-builder

on:

  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase github.repository_owner
        run: |
          echo "REPOSITORY_OWNER=`echo ${{github.repository_owner}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      # Step 4: Build and push image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfiles/build.dockerfile
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/picktheday/leptos-builder:latest
          push: true