name: Build Pick The Day

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # steps:
    #   # Step 1: Checkout the repository
    #   - name: Checkout repository
    #     uses: actions/checkout@v3

    #   # Step 2: Install Rust
    #   - name: Set up Rust
    #     uses: actions-rs/toolchain@v1
    #     with:
    #       toolchain: nightly
    #       override: true
    #       target: wasm32-unknown-unknown
