//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use dashmap::DashMap;
use once_cell::sync::Lazy;
use std::sync::Arc;
use types::PublicId;
pub extern crate sea_orm;

pub mod db;
pub mod error;
pub mod prelude;
pub mod types;

pub mod dates;
pub mod plans;
pub mod users;

// Define the cache using `Lazy` and `DashMap`
static ID_MAP_CACHE: Lazy<Arc<DashMap<PublicId, i32>>> = Lazy::new(|| Arc::new(DashMap::new()));
